config/routes.rb
Training::Application.routes.draw do
  resources :posts
  resources :pages

  get "pages/index"
  root :to => 'pages#index'
  %w[about contact cv].each do |page|
    get page, controller: "pages", action: page
  end

  

end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
	#attr_accessible :title, :slug, :blurb, :content
	#validates :blurb, :length => { :minimum => 10 }
	# validates :blurb. length => { :in => 10..255 }
	#validates :blurb, :length => { :in => 10..255 }, :format => { \
	#			:with => /^\A[a-zA-Z\d ]+\z/, \
	#			:message => "Only letters allowed", \
	#			:multiline => true }
	validates :body, :blurb, :title, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :ediy, :update, :destroy]

  def index
  	@notice = "This came from the pages controller pages_controller.rb"
  	@pages = Page.all
  end

  def about
  end

  def new
  	@page = Page.new
  end

  def create
  	@page = Page.new(page_params)
  	@page.save
  	redirect_to action: :show, id: @page.id
  end

  def show
  end

  private
  	# Use callbacks to share common setup to constraints between actions.
  	def set_page
  		@page = Page.find(params[:id])
  	end

  	# Never trust parameters from the scary internet, only allow the white list through.
  	def page_params
  		params.require(:page).permit(:title, :slug, :content)
  	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :blurb, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Training</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-widh, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", :media => "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="navbar-inner">
      <div class="container-fluid">
        <a class="brand">Jump Start Rails</a>
      </div>
    </div>
  </div>

  <div class="container-fluid">
    <div class="row-fluid">
      <div class="span3">
        <%= render "/shared/menu" %>
      </div>

      <div class="span9">
      	<%= yield %>
      </div>
    </div>
    <hr/>
    <footer></footer>
  </div>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/index.html.erb
<pre>>>>start [app/views/pages/index.html.erb]</pre>
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>
<p><%= @notice %></p>
<% content_for(:note) do %>
	<p>This could be different for each view.</p>
<% end %>
<p><%= link_to "About this site", '/about' %></p> 

<h1>Listing pages</h1>
<table>
  <thead>
    <th>Title</th>
    <th>Slub</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </thead>
  <tbody>
  <% @pages.each do |page| %>
    <tr>
      <td><%= page.title %></td>
      <td><%= page.slug %></td>
      <td><%= page.content %></td>
    </tr>
  <% end %>
  </tbody> 
</table>

<%= link_to "New Page", new_page_path %>

<pre>>>>end [app/views/pages/index.html.erb]</pre>

app/views/pages/new.html.erb
<%= form_for(@page) do |f| %>

  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :slug %><br />
    <%= f.text_field :slug %>
  </p>

  <p>
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

app/views/pages/show.html.erb
<p>
  <strong>Title</strong>
  <%= @page.title %>
</p>

<p>
  <strong>Slug</strong>
  <%= @page.slug %>
</p>

<p>
  <strong>Content</strong>
  <%= @page.content %>
</p>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :blurb %><br>
    <%= f.text_field :blurb %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Blurb</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.blurb %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Blurb:</strong>
  <%= @post.blurb %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/shared/_menu.html.erb
<ul class="nav nav-list">
  <li class="nav-header">Sidebar</li>
  <li class="active"><a href="#">Link</a></li>
  <li class="nav-header">Sidebar</li>
  <li><a href="#">link</a></li>
  <li><a href="#">link</a></li>
  <li class="nav-header">Sidebar</li>
  <li><a href="#">link</a></li>
</ul>